package-lock.json, packages/contented-preview/package.json
All dependencies that are required need to be present in `package.json`, since hoisting isn't guarantee if the consumer don't use what we use.
=> fix(contented-preview): add missing deps that preview need

.eslintrc, .prettierignore
Ignore `out` and `*.js` outputs.
=> chore(lint): add more ignore rules for linting

package-lock.json, packages/contented-example/docs/01:overview.md, packages/contented-example/docs/04:markdown.md, packages/contented-preview/src/styles/prose.css, packages/contented-processor/package.json, packages/contented-processor/unified.ts
Add `remark-directive` and `remark-directive-rehype` into the unified processor.
---
For convenience, I added default admonitions styling.
```markdown
:::div{class="admonitions"}
This is `div{class="admonitions"}`.
:::
```
Also added .prose h1,h2,.. auto link styling.
=> feat(contented-processor): add directive processing, with ssg auto-styling admonitions

index.d.ts, packages/contented-example/contented.js, packages/contented-example/docs/01:overview.md, packages/contented-example/docs/03:api.md, packages/contented-example/docs/04:markdown.md, packages/contented-preview/contentlayer.config.js, packages/contented-preview/src/pages/[[...slug]].page.jsx, packages/contented-preview/src/pages/_components/ContentHeadings.jsx
- Moved `path`, `sections`, `contentHeadings` to default computed fields.
- Moved `title: string`, `description: string` & `tags: string[]` to default fields.
=> chore(contented-processor): add default fields for convenience

packages/contented-preview/contentlayer.config.js
For convenience, add `node_modules` to `contentDirExclude` for any repo that uses `contented.js` at the root.
=> chore(content-preview): ignore node_modules

.gitignore, .idea/contented.iml, packages/contented-preview/cli.js, packages/contented-preview/package.json, packages/contented/build-preview.js, packages/contented/package.json, packages/contented/src/commands/ContentedPreview.ts, packages/contented/src/commands/GenerateCommand.ts, packages/contented/src/commands/WriteCommand.ts
Remove npm spawning, `contented-preview` will be copied over to `contented` and have all the files it needs to spawn preview without requiring previous installation into `node_modules`.
=> chore(contented): contented-preview have its own package.json now

package-lock.json, packages/contented-preview/package.json
Since `contented` cli will `npm i` the `contented-preview`, version lock without `^` will prevent deps drift.
=> chore(contented-preview): version lock all the deps due to "npm i" drift

packages/contented-pipeline/src/Pipeline.ts, packages/contented-processor/src/ContentedProcessor.ts
You can specify and create your own `ContentedPipeline` in the `pipelines: [ {processor: ... }]` field now. The key/type `md` is the short form of the built-in `MarkdownPipeline`.
=> feat(contented-processor): allow contented-pipeline to be injected

packages/contented-pipeline/src/Pipeline.ts, packages/contented-processor/src/ContentedProcessor.ts
By default it provides, a built-in processor called `'md'`. Otherwise, you can provide a string, and it will `import(processor)` module with default exporting ContentedPipeline.
=> feat(contented-processor): instead of providing the ContentedPipeline, ES import it

packages/contented-example/contented.config.js, packages/contented-example/package.json, packages/contented-pipeline-md/src/plugins/RehypeMermaid.ts, packages/contented-pipeline/src/Pipeline.ts, packages/contented-processor/src/ContentedProcessor.ts, packages/contented-processor/src/ContentedProcessor.unit.ts
This allows injection of custom `ContentedPipeline` into the processor field. 
```ts
processor: 'md' | (new (pipeline: Pipeline) => ContentedPipeline);
```
=> feat(contented-processor): revert old behavior of allowing custom Pipeline to be injected

package.json, packages/contented-pipeline-md/src/MarkdownPipeline.ts
Refactor `MarkdownPipeline` to allow parts that you want to override to be easily overridable.
=> refactor(contented-pipeline-md): refactor MarkdownPipeline for easier extendability

packages/contented-pipeline-jest-md/src/JestMarkdownPipeline.unit.ts, packages/contented-pipeline-md/src/MarkdownPipeline.ts, packages/contented-pipeline-md/src/MarkdownPipeline.unit.ts, packages/contented-pipeline/src/Pipeline.ts, packages/contented-pipeline/src/Pipeline.unit.ts, packages/contented-processor/src/ContentedProcessor.ts, packages/contented-processor/src/ContentedProcessor.unit.ts, packages/contented/src/commands/WatchCommand.ts, packages/contented/src/commands/WriteCommand.ts
Refactor Pipeline to allow `process()` to return multiple FileContent per input file.
=> feat(contented-pipeline): allow Pipeline to generate multiple FileContent per file

packages/contented/src/commands/BaseCommand.ts, packages/contented/src/commands/BuildCommand.ts, packages/contented/src/commands/GenerateCommand.ts, packages/contented/src/commands/WatchCommand.ts, packages/contented/src/commands/WriteCommand.ts, packages/contented/src/commands/contented/ContentedPreview.ts, packages/contented/src/commands/contented/ContentedWalker.ts, packages/contented/src/commands/contented/ContentedWatcher.ts
As per the title, this refactor keeps `contented` concerns in the `./contented` directory while commands sit at the root.
=> refactor(contented): move walker & watcher logic into ./contented

packages/contented-pipeline-jest-md/src/JestMarkdownPipeline.unit.ts, packages/contented-pipeline-md/src/MarkdownPipeline.unit.ts, packages/contented-pipeline/src/Pipeline.ts, packages/contented-pipeline/src/Pipeline.unit.ts, packages/contented-processor/src/ContentedProcessor.ts
As per the title, allows customized ContentedPipeline to have access to `rootPath` to know where is the project root is at.
=> chore(contented-pipeline): inject rootPath into ContentedPipeline

packages/contented/src/commands/contented/ContentedWatcher.ts
Add `**/.contented`, `**/node_modules`, and `**/.turbo` for glob pattern ignore.
Introduced in `@parcel/watcher` `2.1.0` — https://github.com/BirthdayResearch/contented/pull/302
=> chore(contented): ContentedWatcher now uses glob pattern ignore

.github/workflows/ci.yml, .github/workflows/release.yml
`.nvmrc` is now the source of truth for node version.
=> chore(workflow): replace all node-version with node-version-file

packages/contented-preview/src/errors/PipelineCollectionNotFoundException.js, packages/contented-preview/src/pages/_components/Header.jsx
Better developer experience when encountering incorrect configuration for pipelines when using contented.
Fixes #318
In the long run, maybe something that checks the `contented.config.js` file and shows the error before even attempting to preview would be an even better experience.
=> chore(contented-preview): throw verbose error for undefined collections

package-lock.json, packages/contented-preview/package.json, packages/contented-preview/tailwind.config.js
As per tailwind `v3.3` this plugin is included by default.
=> chore(contented-preview): remove @tailwindcss/line-clamp plugin

packages/contented-pipeline-md/src/MarkdownPipeline.unit.ts, packages/contented-pipeline-md/src/plugins/RemarkFrontmatter.ts, packages/contented-processor/fixtures/Foo.Bar.md, packages/contented-processor/src/ContentedProcessor.unit.ts
Parse the first heading as title when no title are present, this keep authoring more natural, not all MD requires frontmatter.
Fixes #397
=> feat(contented-pipeline): parse the first heading as title when no title are present

packages/contented-example/contented-example-lorem/[0]lorem-1.md, packages/contented-example/contented-example-lorem/[1]lorem-2.md, packages/contented-example/contented.config.js, packages/contented-example/docs/01-index.md, packages/contented-example/docs/03-api.md, packages/contented-example/docs/04-markdown.md, packages/contented-example/docs/09-Others/02-limitations.md, packages/contented-example/docs/09-Others/99-contributing.md, packages/contented-example/docs/09-ballad.md, packages/contented-example/jest/Pipelines/JestMarkdown.spec.ts, packages/contented-preview/src/pages/[[...slug]].page.jsx
The title should be part of the docs as a heading, this is a breaking change.
```diff
---
- title: Title
description: Describing
---
+ # Title
Your content.
```
=> feat(contented): title should be part of the docs

package.json
Set engines in `package.json` for contented.
=> chore(workflow): set package.json engines

package-lock.json, package.json
As per title, so that it is more flexible.
=> chore(workflow): set engines to `"npm": "^9.0.0"`

packages/contented-processor/src/ContentedCodegen.ts
Generate basic types for ${type}Index for better DX when working with `contented build`.
=> chore(contented-processor): generate basic `index.d.ts` for `${type}Index`

packages/contented-preview/src/pages/_components/ContentNavigation.jsx
=> fix(contented-preview): with `ContentNavigation` non-unique react key

packages/contented-example/docs/04-markdown.md, packages/contented-pipeline-md/src/plugins/RemarkCodeblock.ts, packages/contented-preview/src/pages/[type]/[[...slug]].page.jsx, packages/contented-preview/src/pages/_components/ContentNavigation.jsx, packages/contented-preview/src/styles/prose.css
````md
::::codeblock-group
:::codeblock-header{filename="example.ts" language="TypeScript"}
```ts
const a: number = 1;
const b: number = 2;
```
:::
:::codeblock-header{filename="example.js" language="JavaScript"}
```js
const a = 1;
const b = 2;
```
:::
::::
````
=> feat(codeblock): codeblock with language selector

packages/contented-preview/src/styles/prose.css
=> chore(contented-preview): set text-left for "codeblock-language-options button"

packages/contented-pipeline-md/fixtures/20-Heading/40-Section Title/200-DeepLink.md, packages/contented-pipeline-md/fixtures/RemarkFrontmatter.md, packages/contented-pipeline-md/fixtures/RemarkLink.md, packages/contented-pipeline-md/src/plugins/RemarkFrontmatter.unit.ts, packages/contented-pipeline-md/src/plugins/RemarkLink.ts, packages/contented-pipeline-md/src/plugins/RemarkLink.unit.ts
Parse `%20` as space for `RemarkLink.ts`, also, add test for `truncate`.
=> chore(contented-pipeline-md): parse `%20` as space

packages/contented-preview/src/styles/prose.css
Similar to `.admonitions`, the tr should influence padding instead of content to allow multiline string rendering.
=> chore(contented-preview): remove table first-child mt and last-child mb

packages/contented-pipeline-md/src/plugins/RemarkFrontmatter.ts, packages/contented-pipeline/src/PipelineField.ts
=> feat(contented): add boolean PipelineField

packages/contented-processor/src/ContentedProcessor.ts, packages/contented-processor/src/ContentedProcessor.unit.ts
=> chore(contented-processor): pipeline.type to support `^[a-zA-Z_$][\w$]*$`
