fuxingloh/contented

netlify.toml
package-lock.json
packages/contented-example/.gitignore
packages/contented-example/docs/01:overview.md
packages/contented-preview/.gitignore
packages/contented-preview/cli.js
packages/contented-preview/package.json

Also fix `contented generate`, to copy .next into the cwd.

feat(netlify): publish contented-example to netlify

---

.github/workflows/ci.yml
lerna.json

Add CI workflow to:
- build
- generate
- lint

chore(workflow): add Build/Generate/Lint CI

---

.github/workflows/release.yml
lerna.json
package-lock.json
package.json

- Removed `lerna`, our workflow is too simple. We don't need it.
- Added `release.yml` workflow to publish all packages into npm under the `@brithdayresearch` scope.

chore(workflow): add npm publishing workflow

---

.github/workflows/release.yml
lerna.json
package-lock.json
package.json

Need `lerna` to tag all dependencies correctly, since they all rely on each other.

fix(workflow): add lerna for version tagging

---

.github/workflows/release.yml
packages/contented-example/package.json

`npm publish --workspaces --access public` to publish all as public.

fix(workflow): set publish to public

---

packages/contented-preview/package.json

chore(contented-preview): add missing deps

---

packages/contented-preview/src/pages/_components/ContentNavigation.jsx

fix(contented-preview): fix spacing of ContentNavigation

---

.eslintrc
package-lock.json
packages/contented-example/docs/04:markdown.md
packages/contented-preview/package.json
packages/contented-preview/src/pages/[[...slug]].page.jsx
packages/contented-preview/src/pages/_app.page.jsx
packages/contented-preview/src/pages/_components/ThemeButton.jsx
packages/contented-preview/src/pages/_components/ThemeContext.jsx
packages/contented-processor/mermaid.ts
packages/contented-processor/unified.ts
tsconfig.json

Add mermaid codeblock to div processing with preview.

feat(contented): add mermaid processing and preview

---

.github/governance.yml
.github/labeler.yml
.github/labels.yml

Add `area/contented-*` governance labels.

chore(governance): add more area governance labels

---

packages/contented-example/docs/01:overview.md
packages/contented-example/docs/04:markdown.md
packages/contented-example/docs/09:ballad.md

Fix title mistakes, add missing content.

chore(contented-example): update documentations to fix writing mistakes

---

.github/workflows/ci.yml
.github/workflows/release.yml
netlify.toml

Fix release workflow and optimize "CI / Build".

chore(workflow): fix release workflow

---

package-lock.json
packages/contented-preview/package.json

We don't need eslint for `contented-preview` since it's a copied site.

chore(contented-preview): remove eslint next, not required

---

packages/contented-processor/src/ContentedPipeline.ts
packages/contented-processor/src/ContentedProcessor.ts

Add ability to declare pattern as an array for pipeline processing.

chore(contented-processor): allow pattern array for pipeline processing

---

packages/contented-processor/src/ContentedPipeline.ts
packages/contented-processor/src/ContentedProcessor.ts
packages/contented-processor/src/ContentedProcessor.unit.ts

Add the ability to sort files in a pipeline.

feat(contented-processor): add sorting of files

---

package-lock.json
packages/contented-processor/package.json

Fixes https://github.com/BirthdayResearch/contented/issues/76

chore(contented-processor): remove deprecated hash deps

---

package-lock.json
packages/contented/package.json
packages/contented/src/commands/WatchCommand.ts
turbo.json

Performant and throttled watcher, this fits contented usecase perfectly.
Fixes #87

chore(contented): use @parcel/watcher

---

packages/contented-preview/src/pages/[[...slug]].page.jsx
packages/contented-preview/src/pages/_components/Header.jsx
turbo.json

- Fix missing anchor link in `Header.jsx`
- Fix page navigation (left side) jumps when content overflow, it should stay the same position regardless of content overflow.
Fixes https://github.com/BirthdayResearch/contented/issues/92

chore(contented-preview): fix styling and missing anchor for Header link

---

packages/contented/src/commands/GenerateCommand.ts
packages/contented/src/commands/WatchCommand.ts
packages/contented/src/commands/WriteCommand.ts
packages/contented/src/commands/contented/ContentedWatcher.ts

feat(contented): improve watch/write to refresh index file when contents require reindex

---

package-lock.json
packages/contented-pipeline-jest-md/src/JestMarkdownPipeline.unit.ts
packages/contented-pipeline-md/package.json

bump(contented-pipeline-md): shiki and @leafac/rehype-shiki to latest

---

.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml

chore(workflows): remove BIRTHDAYRESEARCH_BOT_GITHUB_TOKEN

---

package-lock.json
packages/contented-preview/package.json

Rollback to next 12.3.0 due to issues with mermaid rendering.

chore(bumps): rollback to next 12.3.0

---

packages/contented-preview/src/pages/[[...slug]].page.jsx

fix(contented-preview): fix mermaid graph to refresh when theme refresh

---

packages/contented-preview/src/pages/[[...slug]].page.jsx
packages/contented-preview/src/pages/_components/ContentNavigation.jsx

chore(contented-preview): navigation ux improvement

---

lerna.json

chore(workflow): add missing packages to lerna

---

packages/contented-preview/src/pages/_components/ContentNavigation.jsx
packages/contented-preview/src/pages/_components/Header.jsx

fix(contented-preview): next 13 <a> within <Link> deprecated

---

package-lock.json
packages/contented-preview/package.json

fix(contented-preview): Added missing lodash dep

---

packages/contented-example/contented-example-lorem/[0]lorem-1.md
packages/contented-preview/src/styles/prose.css

Fix links not displaying in headers, which may be useful if user wants the title to be a link to somewhere else.
Fixes #308

fix(contented-preview): links in headers not displaying properly

---

package.json
packages/contented-example/package.json
packages/contented-pipeline-jest-md/package.json
packages/contented-pipeline-md/package.json
packages/contented-pipeline/package.json
packages/contented-preview/package.json
packages/contented-processor/package.json
packages/contented/package.json
packages/jest-preset/package.json

chore(project): add lint-staged and sort all package.json

---

.github/workflows/ci.yml

As per title to take advantage of merge queue.

chore(workflows): setup on: merge_group

---

.github/renovate.json
package-lock.json
package.json
packages/contented-pipeline-jest-md/package.json
packages/contented-pipeline-md/package.json
packages/contented-pipeline/package.json
packages/contented-processor/package.json
packages/contented/package.json
packages/jest-preset/jest-preset.js
packages/jest-preset/package.json

Migrate all usage of sticky from `@birthdayresearch/sticky-` to `@stickyjs/`.

chore(deps): migrate usage of sticky from `@birthdayresearch/sticky-` to `@stickyjs/`

---

.github/renovate.json

chore(workflow): update renovate.json

---

package-lock.json

Clean reinstall of dependencies.

chore(deps): reinstall package-lock.json

---

packages/contented-pipeline/fixtures/Example.md
packages/contented-pipeline/src/Pipeline.unit.ts
packages/contented-processor/src/ContentedProcessor.unit.ts

chore(testing): improve test coverage

---

packages/contented-preview/src/pages/_components/ContentHeadings.jsx
packages/contented-preview/src/pages/_components/ContentNavigation.jsx

chore(contented-preview): should heading 3 on aside

---

packages/contented-example/contented-example-lorem/[0]lorem-1.md
packages/contented-example/contented-example-lorem/[1]lorem-2.md
packages/contented-example/docs/03-api.md
packages/contented-preview/src/styles/prose.css

Update content structure to be more "natural" in terms of how headings should be structured so that it's easier to test how well downstream template fit into this structure.

chore(contented-example): update content structure 

---

.github/workflows/ci.yml
.github/workflows/release.yml

chore(workflows): set permission for workflows

---

packages/contented/src/index.ts

feat(contented): Programmatic API for Contented

---

packages/contented/src/index.ts

fix(contented): logic `watch: boolean` was flipped wrongly

---

packages/contented-example/docs/01-index.md
packages/contented-example/package.json
packages/contented-pipeline-jest-md/src/JestMarkdownPipeline.ts
packages/contented-pipeline-md/src/MarkdownPipeline.ts
packages/contented-pipeline/src/Pipeline.ts
packages/contented-preview/src/pages/_components/ContentNavigation.jsx
packages/contented-preview/src/pages/_components/Header.jsx
packages/contented-preview/src/pages/_components/ThemeButton.jsx
packages/contented-preview/src/styles/prose.css
packages/contented/src/commands/BuildCommand.ts
packages/contented/src/commands/GenerateCommand.ts
packages/contented/src/commands/WatchCommand.ts
packages/contented/src/commands/contented/ContentedWatcher.ts

Clean up `contented-pipeline-md` so that downstream extending on top of this pipeline have an easier time working with files.

feat(contented): QOL cleanup for `contented-pipeline-md`

---

packages/contented-example/contented.config.mjs
packages/contented-preview/src/pages/[[...slug]].page.jsx
packages/contented-preview/src/pages/[type]/[[...slug]].page.jsx
packages/contented-preview/src/pages/_components/ContentNavigation.jsx
packages/contented-preview/src/pages/_components/Header.jsx
packages/contented-preview/src/pages/index.page.jsx

feat(contented-preview): folder type is now part of url

---

packages/contented-pipeline/src/Pipeline.ts
packages/contented-processor/src/ContentedCodegen.ts
packages/contented/src/commands/contented/ContentedPreview.ts

chore(contented): use non-promise fs for blocking file IO

---

packages/contented-example/contented.config.mjs
packages/contented-example/docs/01-about.md
packages/contented-example/docs/04-markdown.md
packages/contented-example/docs/09-Others/02-limitations.md
packages/contented-pipeline-md/src/plugins/RemarkLink.ts
packages/contented-pipeline/src/Pipeline.ts
packages/contented-processor/src/ContentedProcessor.ts

feat(contented): support for auto relative linking

---

packages/contented-preview/src/styles/prose.css

feat(contented-preview): add table-auto and table-fixed support

---

packages/contented-preview/src/pages/_components/ContentNavigation.jsx
packages/contented-preview/src/pages/_components/Header.jsx
packages/contented-preview/tailwind.config.js

chore(contented-preview): move Pipeline into side nav for mobile

---

README.md

chore(contented): update examples

---

packages/contented-preview/src/styles/prose.css

chore(contented-preview): reduce admonitions intensity

---

packages/contented-preview/src/styles/prose.css

chore(contented-preview): add down caret for "codeblock-language-selected"

---

packages/contented-pipeline-md/src/plugins/RemarkFrontmatter.ts

fix(contented-pipeline-md): replace `\n` in description to fix SEO

---

packages/contented-pipeline/src/Pipeline.ts

feat(contented-pipeline): pipeline transform to include file

---

package-lock.json
packages/contented/package.json

Reverts levaintech/contented#586

chore(deps): revert "bump(deps): update dependency @parcel/watcher to ^2.3.0"

---

packages/contented-pipeline-md/src/plugins/RemarkFrontmatter.ts
packages/contented-pipeline/src/PipelineField.ts
packages/contented-processor/fixtures/frontmatter-remap.md
packages/contented-processor/fixtures/frontmatter.md
packages/contented-processor/src/ContentedProcessor.unit.ts

feat(contented-pipeline): add type: 'object' parsing

---

package-lock.json
packages/contented-example/contented.config.mjs
packages/contented-example/package.json
packages/contented-pipeline/src/Pipeline.ts
packages/contented-processor/package.json
packages/contented-processor/src/ContentedProcessor.ts

chore(contented): don't ship jest-md by default

---

packages/contented-pipeline-md/fixtures/Features.md
packages/contented-pipeline-md/src/MarkdownPipeline.unit.ts

Add more scenarios to increase test coverage.

chore(contented): add more test coverage

---

package.json
packages/jest-preset/package.json
packages/tsconfig/package.json

chore(workspace): set version

---

.github/workflows/release.yml
package.json
packages/contented-pipeline-md/package.json
packages/contented-pipeline/package.json
packages/contented-processor/package.json
packages/contented/cli.js
packages/contented/package.json
packages/jest-preset/package.json
packages/tsconfig/package.json
pnpm-lock.yaml

chore(workspace): fix release workflow

---

package.json

chore(workspace): setup upper version limit for engines

---

.github/renovate.json
package.json
pnpm-lock.yaml

chore(workflows): add eslint group to renovate.json
